### PR TITLE
Fix the app crash when run on android api level <= 23

### PR DESCRIPTION
**Pull request by danielle-Cman**
Adapt run all android api level

#### What's this PR does?
Fix the app crash when run on android api level <= 23
Adapt run all android api level.

#### Which issue(s) is it related to?
related in function
```
private void updateNotificationMediaStyle()
```
The current code:
```
 if (!(Build.MANUFACTURER.toLowerCase(Locale.getDefault()).contains("huawei") && Build.VERSION.SDK_INT < Build.VERSION_CODES.M)) {
```
We should compare android device have no `huawei` and `Build.VERSION.SDK_INT > Build.VERSION_CODES.M`
```
 if (!Build.MANUFACTURER.toLowerCase(Locale.getDefault()).contains("huawei") && Build.VERSION.SDK_INT > Build.VERSION_CODES.M) {
```
#### Screenshots (if appropriate)
Because i test on emulator and the app crash so i cant take a screenshots.
#### How to test:
We could run on emluator with android api level > 23 and <= 23.

### CODE REVIEW

**Comment by tanguyantoine** [comment]
thank you

**Comment by tanguyantoine** [comment]
published under `0.10.8`

**Comment by danielle-Cman** [comment]
Thank you!

**Comment by ouabing** [comment]
This change just disabled notification media style for all the Huawei devices and also all the Android 6.0 devices. Shall we revert it?

**Pull request merged**
