### PR TITLE
Unified index.ios.js and index.android.js

### PR DESCRIPTION
**Pull request by Ayc0**
#### What's this PR do?
Get rid of the index.ios.js and index.android.js and have a unified index.js

### CODE REVIEW

**Comment by Ayc0** [comment]
We spoke about this in the #115 so there is the PR

**Comment by tanguyantoine** [comment]
https://github.com/tanguyantoine/react-native-music-control/pull/106/files#diff-168726dbe96b3ce427e7fedce31bb0bc

**Comment by Ayc0** [comment]
@tanguyantoine done

**Comment by tanguyantoine** [comment]
Question (non blocking) : What about having `constants.android.js`and `constants.ios.js` to prevent multiple checks? 

This way we could do something like :

```js
import { 
  STATE_PLAYING,
  STATE_PAUSED,
  ...
} from './constants'
```

@kesha-antonov is this PR ok for you?

**Comment by Ayc0** [comment]
I've done it this way because it was faster but yeah, i can export every consts in a different file

**Comment by tanguyantoine** [comment]
LGTM, @Guichaguri good to ship?

**Comment by Guichaguri** [comment]
Yeah :D

**Comment by tanguyantoine** [comment]
@Guichaguri should we deprecate this repo in favor of https://github.com/react-native-kit/react-native-track-player ?

**Comment by Guichaguri** [comment]
It's up to you. I don't really have a lot of time to work on this react-native-music-control anyway.
You can add a notice to the readme and keep accepting PRs so other devs that still need this one can maintain it.

**Comment by DanNi0130** [comment]
@tanguyantoine @Guichaguri Could please keep this open for devs like me that need the controls but not the player itself?

**Comment by Guichaguri** [comment]
@DanNi0130 Yes, I think the objective is to not shutdown this project completely. Just out of curiosity, why do you need music controls but not the player?

**Comment by DanNi0130** [comment]
I am writing a podcast app so I need more granular controls than most players provide (features like on the fly EQing, shortening silences, etc.). These are features that probably wouldn't be very useful for music/radio apps, so I had to write the player myself, this module is perfect for pairing with my own custom player.

**Comment by Guichaguri** [comment]
Fair enough. We actually plan on implementing an EQ in react-native-track-player at some point. It will be pretty useful for both music and podcast apps.

For now, we are in the process of splitting the Chromecast part into an addon module, and redesigning it to make it work with Google Cast, AirPlay (on iOS), DLNA and Miracast.

**Comment by DanNi0130** [comment]
That sounds cool, I'll keep an eye on that, a good Chromecast/AirPlay module would be awesome.

**Pull request merged**
