### PR TITLE
Add stopControl method on iOS

### PR DESCRIPTION
**Pull request by Ayc0**
#### What's this PR do?
Proposal for issue #114

### CODE REVIEW

**Comment by tanguyantoine** [comment]
LGTM, thank you for this stuff. @Guichaguri  do you have something similar for Android ?

**Comment by Ayc0** [comment]
@tanguyantoine I can do something similar for Android

**Comment by tanguyantoine** [comment]
Awesome

**Comment by Ayc0** [comment]
@tanguyantoine why is the code of index.android.js and index.ios.js nearly similar except for the definition of the consts at the top ?
You should have a file in which you define the const for android and ios and import those in a `index.js` file

the only real difference is `DeviceEventEmitter.addListener` for android and `new NativeEventEmitter(NativeMusicControl)` for iOS but you can detect the platform here with ReactNative.Platform === ios or === android

**Comment by Ayc0** [comment]
@tanguyantoine this MR should be done

**Comment by tanguyantoine** [comment]
LGTM

As discussed in #106 we would rather have a dedicated PR to merge index.ios and index.android 

@kesha-antonov started this stuff. 
@Guichaguri it sounds like everyone want to merge these to files, thoughts?

**Comment by tanguyantoine** [comment]
published as 0.5.0

**Comment by Guichaguri** [comment]
@tanguyantoine I'm okay with that :)

**Comment by Ayc0** [comment]
I can work on a PR for the index

**Comment by Guichaguri** [comment]
There is already #79, but it's outdated, so a new PR might be a good idea :)

**Pull request merged**
