### PR TITLE
Fix Illegal null AudioFocusRequest exception 

### PR DESCRIPTION
**Pull request by matinzd**
#### What's this PR does?
Fixes Illegal null AudioFocusRequest exception

#### Which issue(s) is it related to?
#260 

#### Screenshots (if appropriate)
(None)

### CODE REVIEW

**Comment by tanguyantoine** [comment]
Could you clean merges commits and rewrite commits title to follow https://www.conventionalcommits.org/en/v1.0.0-beta.4/

This allows auto versioning :pray:

**Comment by matinzd** [comment]
> Could you clean merges commits and rewrite commits title to follow https://www.conventionalcommits.org/en/v1.0.0-beta.4/
> 
> This allows auto versioning 🙏

Merges cleaned

**Comment by tanguyantoine** [comment]
Why is it a breaking change?

**Comment by matinzd** [comment]
I dont know how to clean up previous merges. How can I do that?

**Pull request merged**
