### PR TITLE
Add declare function typescript

### PR DESCRIPTION
**Pull request by tiendn**
#### What's this PR do?
Add ```Typescript``` define function for VSCode/WebStorm ...

### CODE REVIEW

**Comment by tanguyantoine** [comment]
@Guichaguri I personally don't use (like :trollface: ) Typescript any objection to this PR ?

**Comment by tiendn** [comment]
haha 😆 , plz commits that 👍

**Comment by Guichaguri** [comment]
@tanguyantoine I've used it once, I don't know if this will work, we'll have to trust @tiendn

**Comment by tanguyantoine** [comment]
new version published

**Pull request merged**
