### PR TITLE
[Android] MediaSession support

### PR DESCRIPTION
**Pull request by Guichaguri**
This PR adds support to MediaSession, and makes the Notification work on top of it
It also uses the support library for the MediaSession and Notification, so they work in any Android version.
I also made changes to the gradle config to make it work properly

Related to #1

### CODE REVIEW

**Comment by Guichaguri** [comment]
Do not merge it yet. I still haven't tested it in a real player, and also, I'm trying to figure out a easy way to install it on Android (maybe supporting `react-native link`?)

**Comment by tanguyantoine** [comment]
It does not support linking ?

**Comment by Guichaguri** [comment]
Everything should work with linking, but I don't know if it registers the package automatically. I'll see about it when I have some free time

**Comment by tanguyantoine** [comment]
Let me know when you are done 👍

**Comment by Guichaguri** [comment]
I think I'm done here.
Changes that you should be aware of:
* Added RN link support (take a look at [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info) with you want to know how they did it in iOS)
* Added a new function: `setPlayback`. It is needed to reduce metadata updates in `setNowPlaying`. (for instance, in iOS, it will download the artwork everytime you want to make an update to playback data)
* Added 5 constants (STATE_ERROR, STATE_STOPPED, STATE_PLAYING, STATE_PAUSED, STATE_BUFFERING) to use with the `state` parameter in `setPlayback`

**Comment by tanguyantoine** [comment]
Awesome. 🎉

**Pull request merged**
