### PR TITLE
fix(package.json): remove unused rnpm object to fix warning in RN 0.60

### PR DESCRIPTION
**Pull request by timmywil**
#### What's this PR does?

Removes `rnpm` from package.json.

#### Which issue(s) is it related to?

None opened

#### How to test:

Install and `react-native link react-native-music-control` with RN 0.60.

### CODE REVIEW

**Comment by tanguyantoine** [comment]
Can you explain why you are removing this line ?

**Comment by timmywil** [comment]
This is just to remove a warning after upgrading to RN 0.60. It now warns about any packages still using `rnpm`, as support will be removed in the future. Is this line needed for something?

**Comment by timmywil** [comment]
> warn The following packages use deprecated "rnpm" config that will stop working from next release:
>  - react-native-music-control: https://npmjs.com/package/react-native-music-control
> Please notify their maintainers about it. You can find more details at https://react-native-community/cli/docs/configuration.md#migration-guide.

**Comment by timmywil** [comment]
Ok, that link to docs is broken. Here's a better one: https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide

**Comment by tanguyantoine** [comment]
@timmywil better clarifying ;-)

**Pull request merged**
