### PR TITLE
fix(android): error can't find symbol Notification

### PR DESCRIPTION
**Pull request by Justkant**
#### What's this PR does?
Fix an android build error

#### Which issue(s) is it related to?
None because the last npm release failed and I found the issue when I tried to use master directly

### CODE REVIEW

**Comment by timmywil** [comment]
I also have this in https://github.com/tanguyantoine/react-native-music-control/pull/281

**Comment by Justkant** [comment]
@timmywil I saw that but I'm not yet on 0.60 to use androidx

**Comment by timmywil** [comment]
Makes sense

**Comment by tanguyantoine** [comment]
thanks

**Comment by tanguyantoine** [comment]
`0.10.5`

**Pull request merged**
