### PR TITLE
implemented pause functionality when the headphones are unplugged for Android

### PR DESCRIPTION
**Pull request by frankros91**
#### What's this PR do?
Android Only

Implements logic in MusicControlReceiver.java that listens to when the headphones are unplugged.  If unplugged, a pause key event is dispatched, similar to if the pause button was pressed in the notification tray.
#### Which issue(s) is it related to?
Issue 101
https://github.com/tanguyantoine/react-native-music-control/issues/101

### CODE REVIEW

**Comment by Guichaguri** [comment]
1. You should use the same broadcast receiver, no need to use another one
2. Don't directly use strings for intent actions, use the constant instead
3. Fix the code style, reformat the code

**Comment by jankarres** [comment]
PR refers to issue #101

**Comment by Guichaguri** [comment]
If you want, I can work on this tomorrow

**Comment by frankros91** [comment]
Not sure why the indentations are all off, might be my editor.  I'll clean up and make a final push in a bit

**Comment by jankarres** [comment]
@Guichaguri Do you see any chance to review this PR in the next few days? This would be awesome!

**Comment by Guichaguri** [comment]
There are still code style issues and the code can be simplified with `AudioManager.ACTION_AUDIO_BECOMING_NOISY`. I'll probably push a commit later today to fix it

**Comment by jankarres** [comment]
Amazing. Thanks @Guichaguri and @frankros91!

**Pull request closed without merging**
