### PR TITLE
Live Indicator for Live Streams (iOS)

### PR DESCRIPTION
**Pull request by ahmetsozkesen**
Implemented Live Indicator for Live Streams.

"isLiveStream" prop added to MusicControl.setNowPlaying method to control iOS media control's live indicator visibility for live streams.

### CODE REVIEW

**Comment by bradleyflood** [comment]
Thanks @ahmetsozkesen Can you please update the README.md to reflect how to use this feature?

Thanks
Brad

**Comment by ahmetsozkesen** [comment]
> Thanks @ahmetsozkesen Can you please update the README.md to reflect how to use this feature?
> 
> Thanks
> Brad

I updated README.md for "isLiveStream" prop. Thanks.

Thanks
Ahmet

**Comment by bradleyflood** [comment]
Hi @ahmetsozkesen thank you. Looks like tanguyantione had to force push some updates, so can you please refresh your PR and try again? Thank you and sorry for the hassle.

**Comment by tanguyantoine** [comment]
Yeah sorry about that 🙏

**Comment by ahmetsozkesen** [comment]
Hi, I edited my PR and patch-1 includes all changes now.

Thank you for your time @bradleyflood and @tanguyantoine

**Comment by bradleyflood** [comment]
This is where I find git confusing, the majority of the proposed commits/changes in this PR already exist in `master` so I don't understand why the diff wants to merge them?

Anyway, @ahmetsozkesen you're going to have to start this PR again from a fresh fork of this project, as this PR has become too messy. Sorry about that. Thanks. I know your changes are only minor! Thank you!

**Pull request closed without merging**
